version: "3.8"

services:
  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=ecr
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
