name: Deploy Local (Python)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build da imagem
        run: docker build -t localhost:5000/meu-app-python .

      - name: Push para Docker Registry local
        run: |
          docker run -d -p 5000:5000 --name registry registry:2 || true
          docker tag localhost:5000/meu-app-python localhost:5000/meu-app-python
          docker push localhost:5000/meu-app-python

      - name: Deploy local
        run: |
          docker stop meu-app-python || true
          docker rm meu-app-python || true
          docker run -d --name meu-app-python -p 3000:3000 localhost:5000/meu-app-python
